### ISSUE TITLE
`spawnd` crashes if `metadata.yml` does not exist

### ISSUE THREAD

**Issue by gtfierro** [immesys/spawnpoint#9]
I'm using the spawnd systemd file, and I didn't have a `metadata.yml` file and the service would not start. Easy enough to work around, but the documentation says that `metadata.yml` is optional

**Comment by jhkolb** [comment]
Yeah, that's because the `systemd` file is using the `spawnd` Docker container, which has as its entrypoint `spawnd run -c /etc/spawnd/config.yml -m /etc/spawnd/metadata.yml`.

It's not really a crash so much as being strict about command line parameters: if you reference a metadata file that does not exist, an error is reported. The same thing would happen if you just ran `spawnd` similarly in terminal.

I suppose the issue is that the Docker container assumes you want to advertise metadata, and that hasn't been documented. So I'll probably need to add some documentation specifically about using the `spawnd` container.

**Comment by gtfierro** [comment]
Okay, that sounds fair. Thanks!

**Comment by jhkolb** [comment]
Clarified the container's assumption about metadata in the `README`.
